/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0-beta3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.aimlabs.gaming.operator.aggregator.controller;

import in.aimlabs.gaming.dto.PlayerBalanceRequest;
import in.aimlabs.gaming.dto.Wallet;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Validated
public interface PlayerBalanceApi {

    /**
     * POST /player-balance : Fetch player balance.
     *
     * @param playerBalanceRequest Player balance Request Object (required)
     * @return successful operation (status code 200)
     */
    @PostMapping(
            value = "/player-balance"
    )
    default Mono<ResponseEntity<Wallet>> playerBalance(@RequestBody() Mono<PlayerBalanceRequest> playerBalanceRequest, ServerWebExchange exchange,
                                                       @RequestHeader String tenant) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"totalBalance\" : 500, \"bonus\" : { \"amount\" : 500, \"total\" : 500, \"onHold\" : 0 }, \"currency\" : \"EUR\", \"cash\" : { \"amount\" : 500, \"total\" : 500, \"onHold\" : 0 } }";
                result = ApiUtil.getExampleResponse(exchange, exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }

}
