/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0-beta3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.aimlabs.gaming.operator.aggregator.controller;


import in.aimlabs.gaming.dto.PlayerTransactionRequest;
import in.aimlabs.gaming.dto.PlayerTransactionResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Validated
public interface PlayerTransactionApi {

    /**
     * POST /player-transaction : Player game transaction
     *
     * @param playerTransactionRequest Player Transaction Request (required)
     * @return successful operation (status code 200)
     */
    @PostMapping(
            value = "/player-transaction"
    )
    default Mono<ResponseEntity<PlayerTransactionResponse>> playerTransaction(@RequestBody Mono<PlayerTransactionRequest> playerTransactionRequest, ServerWebExchange exchange,
                                                                              @RequestHeader String tenant) {
        Mono<Void> result = Mono.empty();
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"rollbackTxnId\" : \"12312314313\", \"playerWallet\" : { \"totalBalance\" : 500, \"bonus\" : { \"amount\" : 500, \"total\" : 500, \"onHold\" : 0 }, \"currency\" : \"EUR\", \"cash\" : { \"amount\" : 500, \"total\" : 500, \"onHold\" : 0 } }, \"processedTxnIds\" : { \"60513c28-b74c-475a-a868-6111f5be205d\" : \"12312314313\" } }";
                result = ApiUtil.getExampleResponse(exchange, exampleString);
                break;
            }
        }
        return result.then(Mono.empty());

    }

}
