/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0-beta3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package in.aimlabs.gaming.operator.aggregator.controller;

import in.aimlabs.gaming.dto.PlayerInitialiseRequest;
import in.aimlabs.gaming.dto.PlayerInitialiseResponse;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

@Validated
public interface PlayerInitialiseApi {

    String mockPlayer = "{ \"playerSettings\" : { \"stakeSettings\" : { \"minStake\" : 0.1, \"maxStake\" : 5 } }, \"totalBalance\" : 500, \"externalToken\" : \"valid-player-session-token\", \"bonus\" : { \"amount\" : 500, \"total\" : 500, \"onHold\" : 0 }, \"currency\" : \"EUR\", \"cash\" : { \"amount\" : 500, \"total\" : 500, \"onHold\" : 0 }, \"playerId\" : \"connect-demo-player\", \"regulationSettings\" : { \"realityCheck\" : { \"jurisdiction\" : \"UKGC\", \"sessionLimit\" : 900, \"elapsedTime\" : 100 } } }";

    /**
     * POST /player-initialise : Initiate player game session. Sends player wallet balance and adhoc settings or regulations.
     *
     * @param playerInitialiseRequest Player Initialise Request (required)
     * @return successful operation (status code 200)
     */

    @PostMapping(
            value = "/player-initialise"
    )
    default Mono<ResponseEntity<PlayerInitialiseResponse>> playerInitialise(@RequestBody() Mono<PlayerInitialiseRequest> playerInitialiseRequest, ServerWebExchange exchange
    , @RequestHeader String tenant) {
        Mono<Void> result = Mono.empty();
        //exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {

                result = ApiUtil.getExampleResponse(exchange, mockPlayer);
                break;
            }
        }
        return result.then(Mono.empty());

    }

}
